#ifndef NSW_PROCON_MASK_H
#define NSW_PROCON_MASK_H

//dpad(directional pad, 十字ボタン)
#define NSW_UP_BUTTON_MASK 0x01
#define NSW_DOWN_BUTTON_MASK 0x02
#define NSW_RIGHT_BUTTON_MASK 0x04
#define NSW_LEFT_BUTTON_MASK 0x08


#define NSW_A_BUTTON_MASK 0x02
#define NSW_B_BUTTON_MASK 0x01
#define NSW_X_BUTTON_MASK 0x08
#define NSW_Y_BUTTON_MASK 0x04

#define NSW_L_BUTTON_MASK 0x10
#define NSW_R_BUTTON_MASK 0x20
#define NSW_ZL_BUTTON_MASK 0x40
#define NSW_ZR_BUTTON_MASK 0x80

#define NSW_L_STICK_BUTTON_MASK 0x0100
#define NSW_R_STICK_BUTTON_MASK 0x0200

#endif //NSW_PROCON_MASK_H